USE manutd_db;
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (30, 'David', 'De Gea', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p51940.png', 1, 'GOALKEEPER', 'I don’t know who is the best goalkeeper in the world at the moment, but I want to be the best.', 'SPAIN');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (24, 'Dean', 'Henderson', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p172649.png', 26, 'GOALKEEPER', 'I work hard every single day to be a better version of myself. At the end of the day, the only competition I’ve got is myself', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (35, 'Tom', 'Heaton', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p21205.png', 22, 'GOALKEEPER', 'I still feel I’ve got an awful lot to give and I’ve got the bit between my teeth.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (27, 'Victor', 'Lindelof', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p184667.png', 2, 'DEFENDER', 'United are one of the biggest clubs in the world and always want to win titles. That’s also my goal.', 'SWEDEN');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (27, 'Eric', 'Bailly', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p197365.png', 3, 'DEFENDER', 'To play football at the highest level is all I have ever wanted to do.', 'COTEDIVOIRE');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (29, 'Phil', 'Jones', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p76359.png', 4, 'DEFENDER', 'I just love to defend. I want to stop goals going in the net.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (28, 'Harry', 'Maguire', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p95658.png', 5, 'DEFENDER', 'It’s an amazing club. It’s a club I’ve always watched and I always looked up to when I was younger', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (28, 'Raphael', 'Varane', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p90152.png', 19, 'DEFENDER', 'I came here because I wanted new emotions and it was exactly what I expected and bigger.', 'FRANCE');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (22, 'Diogo', 'Dalot', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p216051.png', 20, 'DEFENDER', 'I will give everything for this club, for this shirt and, hopefully, help the club to win. That’s the most important thing.', 'PORTUGAL');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (26, 'Luke', 'Shaw', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p106760.png', 23, 'DEFENDER', 'I’ve got the freedom to play and that gives me the confidence in what I want to do to help the team.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (28, 'Alex', 'Telles', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p152590.png', 27, 'DEFENDER', 'This is a once-in-a-lifetime opportunity. I’m going to give everything to fight for the club.', 'BRAZIL');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (23, 'Aaron', 'Wan-Bissaka', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p214590.png', 29, 'DEFENDER', 'Every kid wants to play for a team like this. It’s an honour to represent this club.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (28, 'Paul', 'Pogba', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p74208.png', 6, 'MIDFIELDER', 'I want to be the midfielder who can do everything, and at the highest levels: shoot, dribble, score, defend.', 'FRANCE');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (33, 'Juan', 'Mata', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p43670.png', 8, 'MIDFIELDER', 'Every kid wants to play for a team like this. It’s an honour to represent this club.', 'SPAIN');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (25, 'Andreas', 'Pereira', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p156689.png', 15, 'MIDFIELDER', 'It’s my dream to play for United on a regular basis.', 'BRAZIL');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (28, 'Jesse', 'Lingard', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p109322.png', 14, 'MIDFIELDER', 'I feel great pride every time I pull the shirt on.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (27, 'Bruno', 'Fernandes', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p141746.png', 18, 'MIDFIELDER', 'To play for United feels incredible. I can promise the fans I will give everything to help bring us success.', 'PORTUGAL');
INSERT INTO players (age, last_name, img_url, squad_number, position, description, nationality)
VALUES (28, 'Fred', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p101582.png', 17, 'MIDFIELDER', 'I will never forget how I felt the day I made my debut at Old Trafford. It was just fantastic.', 'BRAZIL');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (33, 'Nemanja', 'Matic', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p62398.png', 31, 'MIDFIELDER', 'Manchester United is one of the biggest clubs in the world and I am very happy to be a part of this great group.', 'SERBIA');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (24, 'Donny', 'van de Beek', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p180184.png', 34, 'MIDFIELDER', 'I am ready to take the next step in my career and there is no higher standard than Manchester United.', 'NETHERLANDS');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (24, 'Scott', 'McTominay', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p195851.png', 39, 'MIDFIELDER', 'You’ve got to keep working hard. The moment you stop is when things can go bad for you.', 'SCOTLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (36, 'Cristiano', 'Ronaldo', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p14937.png', 7, 'ATTACKER', 'History has been written in the past and history will be written once again. You have my word.', 'PORTUGAL');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (25, 'Anthony', 'Martial', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p148225.png', 9, 'ATTACKER', 'I love Manchester United, I love the fans, they give me a lot of joy.', 'FRANCE');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (23, 'Marcus', 'Rashford', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p176297.png', 10, 'ATTACKER', 'I have always been a United fan, so to be playing in the first team really is a dream come true.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (20, 'Mason', 'Greenwood', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p220688.png', 11, 'ATTACKER', 'I want show everyone what I can do really. I just want to show everyone why I’m here.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (21, 'Jadon', 'Sancho', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p209243.png', 25, 'ATTACKER', 'Growing up, United was one of the biggest clubs that everyone knows. So I’m very happy to be wearing this jersey now.', 'ENGLAND');
INSERT INTO players (age, first_name, last_name, img_url, squad_number, position, description, nationality)
VALUES (34, 'Edinson', 'Cavani', 'https://resources.premierleague.com/premierleague/photos/players/250x250/p40720.png', 21, 'ATTACKER', 'I am here with a real desire to work hard and to achieve big things with Manchester United.', 'URUGUAY');
INSERT INTO `news_articles`(`created`, `updated`, `title`, `img_url`, `text`)
VALUES ('2021-10-28 11:30', '2021-10-28 11:30', 'Conte keen on Manchester United job as players doubt Solskjær’s capability', 'https://d3vlf99qeg6bpx.cloudfront.net/content/uploads/2021/05/31074639/Antonio.Conte-1.jpg', 'Antonio Conte would be open to discussing taking over at Manchester United if Ole Gunnar Solskjær were sacked, while it emerged on Monday that several players are questioning whether the Norwegian can take the team any further. Several dressing-room sources have told the Guardian that Sunday’s 5-0 capitulation to Liverpool at Old Trafford has crystallised a lack of belief in Solskjær being a good enough manager for United. The 48-year-old is considered tactically underwhelming, while being well-liked by the squad and within the wider club.
United are thought to be seriously considering Solskjær’s future after taking one point from their past four Premier League games. Joel Glazer, who heads the American family’s ownership, resides in Florida, five hours behind the UK, so any decision may be taken later on Monday. The managing director, Richard Arnold, is understood to have cancelled all appointments on Monday to hold talks with Glazer. Conte has not received any formal contact from United although it is believed he has been sounded out should a vacancy arise in the coming days. Although the Italian is reluctant to take up a position during a season, he would make an exception for United because he considers the club a special opportunity. The 52-year-old would want to understand United’s vision before committing. Conte has been out of work since leaving Internazionale in May, having signed off his two seasons there with the Serie A title, the fourth in Italy of his career. Conte also claimed the Premier League in his opening campaign at Chelsea in 2016-17 and the FA Cup the following year.');
INSERT INTO `news_articles` (`created`, `updated`, `title`, `img_url`, `text`)
VALUES ('2021-10-28 11:31', '2021-10-28 11:30', 'Cristiano Ronaldo says he will close mouths of critics by winning things at Manchester United', 'https://e0.365dm.com/21/10/2048x1152/skysports-cristiano-ronaldo_5555614.png', 'Cristiano Ronaldo said he will "close the mouths" of his critics and that they "do not want to see" his defensive work in an exclusive interview with Sky Sports.
Ronaldo’s return to Manchester United on Transfer Deadline Day was greeted with fanfare and the six goals of his second spell at Old Trafford have proved pivotal in Europe and the Premier League, providing late winners in both of their Champions League group-stage victories to date. However, United’s ropey form has not seen the five-time Ballon d’Or winner immune from criticism. Data graphics have put the 36-year-old at the bottom of the pressing charts for forwards across the Premier League, which coupled with the club’s perceived soft underbelly has raised questions about Ronaldo’s overall impact. In a wide-ranging interview with Sky Sports ahead of a showdown with Liverpool on Sky Sports Premier League this Sunday, the record international goalscorer hit back at his critics as not wanting to see the positives of his game, and said even as he enters his 20th season as a professional, his winning desire still burns as brightly as ever.
He said: "I know when the team needs my help defensively. But my role in the club is to win, help the team to win and to score goals - [the defensive side] is part of my job. "The people who don’t want to see that is because they don’t like me but to be honest I’m 36, I win everything so am I going to be worried about the people who say bad things about me? I sleep good at night. I go to my bed with my conscience very good. Keep going with that because I will still close mouths and win things.
"Criticism is always part of the business. I’m not worried about that. And I see it as a good thing to be honest. If they worry about me or they speak about me, it’s because they know my potential and value in football still. So it’s good. I’ll give you an example: if you’re in a school and you’re the best student, you ask the worst student if he likes the best, they’ll say they don’t like him.');
INSERT INTO `roles` (`name`) VALUES ('ADMIN');
INSERT INTO `roles` (`name`) VALUES ('USER');
INSERT INTO `products` (`name`, `quantity`, `price`, `img_url`) VALUES ('Manchester United Home Shirt 2021-22', 10, 60.99, 'https://images.footballfanatics.com/manchester-united/manchester-united-home-shirt-2021-22_ss4_p-12052601+u-at664r59yn8qgpq61tz1+v-206a8d38ca49417f845b1e6711c02106.jpg?_hv=1&w=900');
INSERT INTO `products` (`name`, `quantity`, `price`, `img_url`) VALUES ('Manchester United Third Shirt 2021-22', 10, 50.99, 'https://images.footballfanatics.com/manchester-united/manchester-united-third-shirt-2021-22_ss4_p-12052548+u-11j173tm5vq2ycw9fyvr+v-2f47135b2bc64b3a8d5cc4b1f32349ad.jpg?_hv=1&w=900');
INSERT INTO `products` (`name`, `quantity`, `price`, `img_url`) VALUES ('Manchester United Away Shirt 2021-22', 10, 50.99, 'https://images.footballfanatics.com/manchester-united/manchester-united-away-shirt-2021-22_ss4_p-12052603+u-b7sp7qmu31as2usy5man+v-765af7e8dd784446a6249a8959f37917.jpg?_hv=1&w=900');
INSERT INTO `products` (`name`, `quantity`, `price`, `img_url`) VALUES ('Manchester United Training Top-Black', 3, 34.99, 'https://images.footballfanatics.com/manchester-united/manchester-united-training-top-black-kids_ss4_p-12052572+u-171vbxc879854n5wrssz+v-73a0d14c0aa647769109c25c11c68a3b.jpg?_hv=1&w=900');
INSERT INTO `products` (`name`, `quantity`, `price`, `img_url`) VALUES ('Manchester United Crest Keyring & Badge Set', 2, 2.99, 'https://images.footballfanatics.com/manchester-united/manchester-united-crest-keyring-and-badge-set_ss4_p-11870207+u-vfgofhxr1l2gli5qx5f9+v-480284eeca6e4b20ab9693b856ef5df3.jpg?_hv=1&w=900');
INSERT INTO `products` (`name`, `quantity`, `price`) VALUES ('Manchester United adidas 3 Pack Face Coverings - Black', 10, 8.99);